"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { getLatestCaseEvent, getOpenActionsForUser, getRecentEventsForUser, getUpcomingItemsForUser, getUserCases } from "@/data/user-cases";
import type { UnifiedCase } from "@/data/unified-case";
import { getMockRole } from "@/data/mock-session";

const date = (value: string) => new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short" }).format(new Date(`${value}T00:00:00`));
export default function MyNyayaDashboard() {
  const [cases, setCases] = useState<UnifiedCase[]>([]); const [role, setRole] = useState<string | null>(null); useEffect(() => { const refresh = () => { setCases(getUserCases()); setRole(getMockRole()); }; refresh(); window.addEventListener("nyaya-demo-case-updated", refresh); window.addEventListener("nyaya-mock-session", refresh); return () => { window.removeEventListener("nyaya-demo-case-updated", refresh); window.removeEventListener("nyaya-mock-session", refresh); }; }, []);
  if (!cases.length) return <main className="wrap dashboard-page"><p className="dashboard-loading">Loading your synthetic workspace…</p></main>;
  const actions = getOpenActionsForUser(cases), upcoming = getUpcomingItemsForUser(cases), updates = getRecentEventsForUser(cases);
  return <main className="wrap dashboard-page"><p className="kicker">{role ? `${role} demo workspace` : "Demo workspace"} · synthetic data</p><h1>Good evening{role ? `, ${role}.` : "."}</h1><p className="dashboard-intro">Here&apos;s what needs your attention.</p><p className="dashboard-summary">{cases.length} active cases <i /> {upcoming.filter((item) => item.type === "hearing").length} upcoming hearings <i /> {actions.length} item{actions.length === 1 ? "" : "s"} need attention</p>
    <section className="dashboard-section dashboard-attention"><div className="dashboard-heading"><span>Needs attention</span><small>{actions.length} item{actions.length === 1 ? "" : "s"}</small></div>{actions.length ? <div className="attention-list">{actions.slice(0, 3).map(({ caseData, ...action }) => <article key={action.id}><div><span>{caseData.caseType}</span><h2>{caseData.title}</h2><b>{action.title}</b><p>{action.description}</p>{action.dueDate && <small>Due before: {date(action.dueDate)}</small>}</div><Link href={`/cases/${caseData.id}`}>Review filing →</Link></article>)}</div> : <p className="calm-empty">✓ Nothing needs your immediate attention.<small>Your tracked cases have no open action items.</small></p>}{actions.length > 3 && <Link className="text-action" href="/my-cases?filter=attention">View all actions →</Link>}</section>
    <div className="dashboard-pair"><section className="dashboard-section"><div className="dashboard-heading"><span>Upcoming</span><Link href="/today">Open today&apos;s court →</Link></div><div className="upcoming-list">{upcoming.slice(0, 4).map((item) => <Link href={item.href} key={item.id}><time>{date(item.date)}</time><div><b>{item.title}</b><p>{item.type === "hearing" ? `Hearing · ${item.subtitle}` : `Due item · ${item.subtitle}`}</p></div></Link>)}</div></section><section className="dashboard-section"><div className="dashboard-heading"><span>Recent updates</span><Link href="/notifications">View notifications →</Link></div><div className="recent-list">{updates.slice(0, 5).map(({ caseData, caseEvent }) => <Link href={`/cases/${caseData.id}`} key={caseEvent.id}><time>{date(caseEvent.occurredAt)}</time><div><span>{caseEvent.type.replaceAll("-", " ")}</span><b>{caseEvent.title}</b><p>{caseData.shortTitle}</p></div></Link>)}</div></section></div>
    <section className="dashboard-section dashboard-cases"><div className="dashboard-heading"><span>My cases</span><Link href="/my-cases">View all cases →</Link></div><div>{cases.slice(0, 4).map((caseData) => <CasePreview caseData={caseData} key={caseData.id} />)}</div></section>
  </main>;
}
function CasePreview({ caseData }: { caseData: UnifiedCase }) { const count = caseData.actionsRequired.filter((item) => item.status === "open").length; const update = getLatestCaseEvent(caseData); return <Link className="dashboard-case" href={`/cases/${caseData.id}`}><div><h2>{caseData.title}</h2><p>{caseData.caseType} · {caseData.court.establishment}</p></div><p><b>Stage</b>{caseData.stage.current}</p><p><b>Next hearing</b>{date(caseData.nextHearing.date)} · {caseData.nextHearing.time}</p><p className={count ? "has-attention" : ""}><b>Attention</b>{count ? `${count} item` : "None"}</p><span aria-label={`Open ${caseData.title}`}>→</span>{update && <small>Updated {date(update.occurredAt)}</small>}</Link>; }
