"use client";

import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { AlertTriangle, CheckCircle2, ChevronRight, FileText, Gavel, Paperclip, Plus, Upload } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import { addDemoOrder, flagDemoFilingNeedsAttention, getRecentCaseEvents, loadDemoCase, markDemoFilingReady, resetDemoCase, rescheduleDemoHearing } from "@/data/demo-case-store";
import type { CaseAction, CaseEvent, UnifiedCase } from "@/data/unified-case";
import { getMockRole } from "@/data/mock-session";
import { roleConfig, type CaseTab, type Role } from "@/data/roles";

type Tab = CaseTab;
const stages = ["Filed", "Scrutiny", "Registered", "Notice", "Hearing", "Evidence", "Arguments", "Decision"];
const priorityRank = { high: 0, medium: 1, low: 2 } as const;

function dateLabel(date: string) { return new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${date}T00:00:00`)); }
function dateParts(date: string) { const parts = new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric" }).formatToParts(new Date(`${date}T00:00:00`)); return { day: parts.find((part) => part.type === "day")?.value ?? "", month: parts.find((part) => part.type === "month")?.value ?? "", year: parts.find((part) => part.type === "year")?.value ?? "" }; }
function typeIcon(type: CaseEvent["type"]) { return type === "order-added" ? <Gavel /> : type === "document-uploaded" ? <Paperclip /> : type.includes("filing") ? <FileText /> : <CheckCircle2 />; }
function actionHref(caseId: string, action: CaseAction) { return action.relatedDocumentId ? `/cases/${caseId}/documents/${action.relatedDocumentId}` : action.relatedFilingId ? `/cases/${caseId}/filings/${action.relatedFilingId}` : `/cases/${caseId}`; }

export default function UnifiedCaseWorkspace({ caseData: initialCase }: { caseData: UnifiedCase }) {
  const [tab, setTab] = useState<Tab>("Overview");
  const [documentFilter, setDocumentFilter] = useState("All");
  const [search, setSearch] = useState("");
  const [caseData, setCaseData] = useState(initialCase);
  const [eventToast, setEventToast] = useState<string | null>(null);
  const [role, setRole] = useState<Role | null>(null);
  const searchParams = useSearchParams();
  const reduceMotion = useReducedMotion();
  const requestedTab = searchParams.get("tab");
  const highlightedDocumentId = searchParams.get("newDocument");
  useEffect(() => { const refresh = () => setRole(getMockRole()); refresh(); window.addEventListener("nyaya-mock-session", refresh); return () => window.removeEventListener("nyaya-mock-session", refresh); }, []);
  const tabs = useMemo<Tab[]>(() => role ? roleConfig[role].tabs : ["Overview", "Timeline", "Filings", "Documents"], [role]);
  useEffect(() => { setCaseData(loadDemoCase(initialCase.id, initialCase)); const match = tabs.find((item) => item.toLowerCase() === requestedTab?.toLowerCase()); if (match) setTab(match); else if (!tabs.includes(tab)) setTab("Overview"); }, [initialCase, requestedTab, tab, tabs]);
  const openActions = useMemo(() => caseData.actionsRequired.filter((action) => action.status === "open").sort((a, b) => priorityRank[a.priority] - priorityRank[b.priority]), [caseData.actionsRequired]);
  const filteredDocuments = useMemo(() => caseData.documents.filter((document) => (documentFilter === "All" || document.category === documentFilter) && document.title.toLowerCase().includes(search.toLowerCase())), [caseData.documents, documentFilter, search]);
  const panel = { initial: reduceMotion ? false : { opacity: 0, y: 7 }, animate: { opacity: 1, y: 0 }, exit: reduceMotion ? undefined : { opacity: 0, y: -5 }, transition: { duration: 0.19 } };
  const currentAction = openActions[0];

  return <div className="unified-case">
    <Link className="back-link" href={role ? roleConfig[role].home : "/my-nyaya"}>← {role ? roleConfig[role].workspace : "My Nyaya"}</Link>
    <header className="unified-case-header">
      <div>
        {caseData.demo && <span className="demo-pill">Demo case</span>}
        <h1>{caseData.title}</h1><p>{caseData.caseType}</p><code>{caseData.id}</code>
        <p className="court-label">{caseData.court.name}<br />{caseData.court.establishment}</p>
      </div>
      <section className="header-stage" aria-label="Current case status">
        <span>Current stage</span><b>{caseData.stage.current}</b>
        <p><em>Official status</em><strong>{caseData.status.label}</strong><br /><time dateTime={caseData.nextHearing.date}>{dateLabel(caseData.nextHearing.date)}</time> · {caseData.nextHearing.time}<br />{caseData.court.courtroom}<br /><em>Presiding judge</em><strong>{caseData.court.judge}</strong></p>
      </section>
    </header>
    {currentAction ? <section className="case-attention" aria-label="Action required">
      <AlertTriangle aria-hidden="true" /><div><span>{openActions.length} item{openActions.length === 1 ? "" : "s"} need{openActions.length === 1 ? "s" : ""} your attention</span><b>{currentAction.title}</b><p>{currentAction.description}{currentAction.dueDate ? ` Due ${dateLabel(currentAction.dueDate)}.` : ""}</p></div>
      <Link href={actionHref(caseData.id, currentAction)}>Review item <ChevronRight aria-hidden="true" /></Link>
    </section> : <section className="case-attention clear" aria-label="No immediate action required"><CheckCircle2 aria-hidden="true" /><div><b>No immediate action required</b><p>There are no open actions in this synthetic case record.</p></div></section>}
    <nav className="unified-tabs" aria-label="Case workspace sections" role="tablist">{tabs.map((item) => <button aria-controls="case-workspace-panel" aria-selected={tab === item} className={tab === item ? "active" : ""} key={item} onClick={() => setTab(item)} role="tab">{item}</button>)}</nav>
    <div className="case-shell"><main aria-label={`${tab} for ${caseData.shortTitle}`} id="case-workspace-panel" role="tabpanel"><AnimatePresence mode="wait">
      {tab === "Overview" && <motion.div key="overview" {...panel}><Overview caseData={caseData} setTab={setTab} /></motion.div>}
      {tab === "Timeline" && <motion.div key="timeline" {...panel}><Timeline caseData={caseData} /></motion.div>}
      {tab === "Filings" && <motion.div key="filings" {...panel}><Filings caseData={caseData} role={role} /></motion.div>}
      {tab === "Documents" && <motion.div key="documents" {...panel}><Documents caseData={caseData} documents={filteredDocuments} filter={documentFilter} setFilter={setDocumentFilter} search={search} setSearch={setSearch} highlightedDocumentId={highlightedDocumentId} role={role} /></motion.div>}
      {tab === "Hearings" && <motion.div key="hearings" {...panel}><RoleContext title="Hearing context" text={`The next synthetic hearing is ${dateLabel(caseData.nextHearing.date)} at ${caseData.nextHearing.time} in ${caseData.court.courtroom}.`} /></motion.div>}
      {tab === "Readiness" && <motion.div key="readiness" {...panel}><RoleContext title="Record readiness" text="This prototype shows filing and document context for human review. It does not assess legal validity or determine an outcome." /></motion.div>}
      {tab === "Proceedings" && <motion.div key="proceedings" {...panel}><RoleContext title="Proceedings and drafts" text="This illustrative workspace can surface a proceeding and draft-review context; final transcription and record approval remain human responsibilities." /></motion.div>}
    </AnimatePresence></main><ActionRail caseData={caseData} action={currentAction} role={role} onReset={() => { if (window.confirm("Reset Nyaya demo to its starting state?")) { setCaseData(resetDemoCase(caseData.id)); setEventToast("Demo restored."); } }} onDemoEvent={(kind) => { const updated = kind === "order" ? addDemoOrder(caseData.id) : kind === "hearing" ? rescheduleDemoHearing(caseData.id) : kind === "attention" ? flagDemoFilingNeedsAttention(caseData.id) : markDemoFilingReady(caseData.id); setCaseData(updated); setEventToast(kind === "order" ? "New order added to the case timeline." : kind === "hearing" ? "Hearing date updated in the case record." : kind === "attention" ? "Filing review action created." : "Filing marked ready in the prototype."); }} /></div>
    {highlightedDocumentId && caseData.documents.some((document) => document.id === highlightedDocumentId) && <div className="case-toast" role="status"><CheckCircle2 aria-hidden="true" /><span><b>Document added to case</b>{caseData.documents.find((document) => document.id === highlightedDocumentId)?.title} is now available in this synthetic case record.</span></div>}
    {eventToast && <div className="case-toast" role="status"><CheckCircle2 aria-hidden="true" /><span><b>Case activity updated</b>{eventToast}</span><button aria-label="Dismiss update" onClick={() => setEventToast(null)}>×</button></div>}
  </div>;
}

function Overview({ caseData, setTab }: { caseData: UnifiedCase; setTab: (tab: Tab) => void }) {
  const hearing = dateParts(caseData.nextHearing.date);
  return <div className="overview-stack">
    <section className="case-panel status-panel"><span className="eyebrow">Official status</span><h2>{caseData.status.label}</h2><p>Your next hearing is scheduled for:</p><div className="status-date"><b>{dateLabel(caseData.nextHearing.date)}</b><span>{caseData.nextHearing.time} · {caseData.court.courtroom}</span></div><p><strong>Purpose</strong><br />{caseData.nextHearing.purpose}</p></section>
    <section className="case-panel plain-language"><span className="eyebrow">What this means</span><p>{caseData.status.plainLanguage}</p><span className="eyebrow">What may happen next</span><p>The court may hear submissions, review documents, issue directions, or schedule another procedural stage.</p></section>
    <section className="case-panel journey-panel"><span className="eyebrow">Case journey</span><div className="case-stage-track">{stages.map((stage) => <div aria-current={stage === caseData.stage.current ? "step" : undefined} className={stage === caseData.stage.current ? "current" : caseData.stage.completedStages.includes(stage) ? "done" : "future"} key={stage}><i aria-hidden="true" /><span>{stage}</span></div>)}</div></section>
    <div className="overview-split"><section className="case-panel hearing-card"><span className="eyebrow">Next hearing</span><div className="hearing-date"><b>{hearing.day}</b><span>{hearing.month.toUpperCase()}<br />{hearing.year}</span></div><h3>{caseData.nextHearing.time} · {caseData.court.courtroom}</h3><p>{caseData.court.name}<br />{caseData.court.establishment}</p><p><strong>Presiding judge</strong><br />{caseData.court.judge}</p><p><strong>{caseData.nextHearing.purpose}</strong></p><Link href="/today">View hearing preview →</Link></section>
    <section className="case-panel activity-card"><span className="eyebrow">Recent activity</span>{getRecentCaseEvents(caseData, 3).map((event) => <div key={event.id}><time dateTime={event.occurredAt}>{dateLabel(event.occurredAt)}</time><b>{event.title}</b><p>{event.plainLanguage || event.description}</p></div>)}<button onClick={() => setTab("Timeline")}>View full timeline →</button></section></div>
    <section className="case-panel people-card"><span className="eyebrow">People</span><div><p><b>Petitioner</b>{caseData.parties.petitioners[0]}</p><p><b>Advocate</b>{caseData.advocates.petitioner[0]}</p><p><b>Respondent</b>{caseData.parties.respondents[0]}</p><p><b>Advocate</b>{caseData.advocates.respondent[0]}</p></div></section>
  </div>;
}

function Timeline({ caseData }: { caseData: UnifiedCase }) { return <section className="case-panel"><span className="eyebrow">Case diary</span><div className="timeline-spine">{getRecentCaseEvents(caseData, caseData.events.length).map((event) => <article key={event.id}><time dateTime={event.occurredAt}>{dateLabel(event.occurredAt)}</time><i aria-hidden="true">{typeIcon(event.type)}</i><div><span>{event.type.replaceAll("-", " ")}</span><h3>{event.title}</h3><p>{event.description}</p>{event.details?.previousDate && event.details.newDate && <p className="event-date-change"><b>{dateLabel(event.details.previousDate)}</b><span>↓</span><b>{dateLabel(event.details.newDate)}</b></p>}{event.plainLanguage && <p className="event-meaning"><b>What this means</b>{event.plainLanguage}</p>}<small className="event-source">Source · {event.sourceSystem?.label ?? (event.source?.type === "filing" ? "Prototype Filing Workflow" : "Synthetic Court Record")}</small>{event.source?.id && (event.source.type === "document" || event.source.type === "order") && <Link href={`/cases/${caseData.id}/documents/${event.source.id}`}>View document →</Link>}{event.source?.id && event.source.type === "filing" && <Link href={`/cases/${caseData.id}/filings/${event.source.id}`}>View filing →</Link>}</div></article>)}</div></section>; }

function Filings({ caseData, role }: { caseData: UnifiedCase; role: Role | null }) { return <section className="case-panel"><div className="tab-heading"><div><span className="eyebrow">Filings</span><h2>Case filings</h2></div>{role === "advocate" ? <Link className="small-action" href={`/file-a-case`}><Plus aria-hidden="true" /> File a fresh case</Link> : <span className="role-readonly">View-only prototype context</span>}</div><p className="filing-disclosure">Statuses below are local prototype-registry states. They do not confirm court or authority approval.</p><div className="filing-list">{caseData.filings.map((filing) => <Link aria-label={`View filing: ${filing.title}`} href={`/cases/${caseData.id}/filings/${filing.id}`} key={filing.id}><div><span className="filing-status">{filing.status}</span><h3>{filing.title}</h3><p>{filing.filingType} · Filed {dateLabel(filing.date)} · {filing.filedBy} · {filing.documentIds.length} document{filing.documentIds.length === 1 ? "" : "s"}</p><small className="filing-status-detail"><b>Prototype registry status</b>{filing.statusDescription}</small></div><ChevronRight aria-hidden="true" /></Link>)}</div></section>; }

function Documents({ caseData, documents, filter, setFilter, search, setSearch, highlightedDocumentId, role }: { caseData: UnifiedCase; documents: UnifiedCase["documents"]; filter: string; setFilter: (value: string) => void; search: string; setSearch: (value: string) => void; highlightedDocumentId: string | null; role: Role | null }) { const filters = ["All", "Filing", "Order", "Submission", "Evidence"]; const highlightedRef = useRef<HTMLElement | null>(null); const canUpload = role === "advocate"; useEffect(() => { highlightedRef.current?.scrollIntoView({ behavior: "smooth", block: "center" }); }, [highlightedDocumentId]); return <section className="case-panel"><div className="tab-heading"><div><span className="eyebrow">Documents</span><h2>Case documents</h2></div>{canUpload ? <Link className="small-action" href={`/cases/${caseData.id}/documents/upload`}><Upload aria-hidden="true" /> Upload document</Link> : <span className="role-readonly">Role-limited view</span>}</div><div className="document-controls"><div aria-label="Filter documents">{filters.map((item) => <button aria-pressed={filter === item} className={filter === item ? "active" : ""} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search documents" aria-label="Search documents" /></div><div className="document-list">{documents.length ? documents.map((document) => <article className={document.id === highlightedDocumentId ? "focused-document" : ""} key={document.id} ref={document.id === highlightedDocumentId ? highlightedRef : undefined}><FileText aria-hidden="true" /><div><h3>{document.title}</h3><p><time dateTime={document.date}>{dateLabel(document.date)}</time> · {document.category} · {document.pages} pages</p><span className="uploaded-by">Uploaded by {document.addedBy}</span>{document.processing && <small>Processing: {document.processing.status.replace("-", " ")} · AI-assisted classification: {document.processing.classification} · Human review available</small>}</div><Link href={`/cases/${caseData.id}/documents/${document.id}`}>View<span className="sr-only"> {document.title}</span></Link></article>) : <div className="empty-state">No documents match this view.</div>}</div></section>; }

function RoleContext({ title, text }: { title: string; text: string }) { return <section className="case-panel"><span className="eyebrow">Role-aware prototype context</span><h2>{title}</h2><p>{text}</p></section>; }
function ActionRail({ caseData, action, role, onReset, onDemoEvent }: { caseData: UnifiedCase; action?: CaseAction; role: Role | null; onReset: () => void; onDemoEvent: (kind: "order" | "hearing" | "attention" | "filing") => void }) { const actions = role ? roleConfig[role].actions : []; return <aside className="unified-action-rail" aria-label="Case actions and metadata"><section className="rail-actions"><span className="eyebrow">Case actions</span>{actions.map((item) => <Link href={item.href} key={item.label}>{item.label} <ChevronRight aria-hidden="true" /></Link>)}{!role && <Link href="/login">Choose mock workspace <ChevronRight aria-hidden="true" /></Link>}</section><section><span className="eyebrow">Court actions</span><Link href="/today">View cause list <ChevronRight aria-hidden="true" /></Link><Link href="/courts">View court information <ChevronRight aria-hidden="true" /></Link></section><section><span className="eyebrow">Document services</span><Link href="/whats-mocked">Request certified copy <small>Prototype</small></Link></section><section><span className="eyebrow">Case at a glance</span><p><b>Case type</b>{caseData.caseType}</p><p><b>Court</b>{caseData.court.name}</p><p><b>Presiding judge</b>{caseData.court.judge}</p><p><b>Current stage</b>{caseData.stage.current}</p><p><b>Next date</b>{dateLabel(caseData.nextHearing.date)}</p><p><b>Last updated</b>{dateLabel(caseData.status.updatedAt)}</p></section><section><span className="eyebrow">Important dates</span><p><b>Next hearing</b>{dateLabel(caseData.nextHearing.date)}</p>{action?.dueDate && <p><b>Document review</b>{dateLabel(action.dueDate)}</p>}</section>{process.env.NODE_ENV !== "production" && caseData.id === "NYA-WB-DEMO-04821" && <section className="demo-events"><span className="eyebrow">Demo events</span><button onClick={() => onDemoEvent("order")}>New order</button><button onClick={() => onDemoEvent("hearing")}>Reschedule hearing</button><button onClick={() => onDemoEvent("attention")}>Filing needs attention</button><button onClick={() => onDemoEvent("filing")}>Mark filing ready</button><button className="demo-reset" onClick={onReset}>Reset demo case</button></section>}</aside>; }
