import Link from "next/link";
import CaseLookup from "@/components/CaseLookup";
import PortalUnifier from "@/components/PortalUnifier";
import { Disclaimer, Footer, Header } from "@/components/SiteChrome";

const roles = [["Litigant", "A plain-language timeline, next date, and shared documents."], ["Advocate", "A single case workspace and listing-ready case brief."], ["Judge", "A focused file view with filings and matter history."], ["Registry / Court staff", "A mock operational queue for complete case records."], ["Stenographer", "A clean hearing context before preparing a record."], ["Police / IO", "A scoped, fictional case-status view for demonstration."]];
const actions = [["⌕", "Find a case", "Search case status and history", "/cases/NYOS-2026-DL-000482"], ["◴", "Check hearings", "Today’s and upcoming demo cause lists", "/whats-mocked"], ["▤", "Orders & documents", "Find and understand court records", "/cases/NYOS-2026-DL-000482"], ["⌂", "Find a court", "Court details, location and information", "/whats-mocked"], ["↥", "File & services", "A guided prototype of available services", "/whats-mocked"], ["⚖", "Advocate services", "Manage cases and client workspaces", "/roles/advocate"]];
export default function Home() { return <><Disclaimer /><Header /><main>
  <section className="journey-hero" id="track"><div className="wrap"><p className="kicker">A single guided journey</p><h1>One place for your<br /><em>court journey.</em></h1><p className="lede">Track cases, understand updates, and access court services without navigating multiple systems.</p><CaseLookup /><div className="hero-links"><Link href="/cases/NYOS-2026-DL-000482">Track a case</Link><span>·</span><Link href="/whats-mocked">View cause lists</Link><span>·</span><Link href="/cases/NYOS-2026-DL-000482">Find orders</Link></div><span className="or-rule">or</span><Link href="#services" className="outline-cta">Explore court services <span>→</span></Link></div></section>
  <section className="actions wrap" id="services"><div className="center-heading"><p className="kicker">Start with your need</p><h2>What do you need to do today?</h2><p>Start with what you need, not which portal to visit.</p></div><div className="action-grid">{actions.map(([icon, title, text, href]) => <Link className="action-card" href={href} key={title}><span className="action-icon">{icon}</span><h3>{title}</h3><p>{text}</p><span className="arrow">→</span></Link>)}</div></section>
  <section className="unification"><div className="wrap unify-layout"><div><p className="kicker">Why Nyaya exists</p><h2>The court system is connected.<br /><em>The digital experience isn&apos;t.</em></h2><p>Nyaya brings scattered touchpoints into one understandable case view — your case, your timeline, and your updates.</p><p className="unify-note">One identity. One case timeline. A simpler way to stay informed.</p></div><PortalUnifier /></div></section>
  <section className="case-journey wrap"><div className="center-heading"><p className="kicker">Your case, explained like a journey</p><h2>Don&apos;t just show the status.<br />Show what it means.</h2></div><article className="journey-card"><div className="journey-card-head"><span className="case-id">NYOS-2026-DL-000482</span><span className="demo-pill">synthetic demo</span><h3>Mehta v. Northstar Supplies</h3></div><div className="journey-steps"><span className="complete">Filed</span><span className="complete">Registered</span><span className="complete">Hearing</span><span>Evidence</span><span>Decision</span></div><div className="journey-explainer"><div><span className="illustrative">Current status</span><h3>Listed for hearing</h3><p>Your next hearing is scheduled for 03 September 2026.</p></div><div><span className="illustrative">What happens next?</span><p>The court will hear submissions from both parties. This plain-language explanation is illustrative.</p></div><Link className="outline-cta" href="/cases/NYOS-2026-DL-000482">View case journey <span>→</span></Link></div></article></section>
  <section className="court-data" id="court-data"><div className="wrap"><div className="data-heading"><div><p className="kicker">Court data</p><h2>Understand the bigger picture.</h2></div><div className="data-tabs"><span>India overview</span><span>States & UTs</span><span>Districts</span><span>Courts</span></div></div><div className="data-preview"><div className="map-placeholder"><span>INDIA</span><i /><i /><i /><i /><i /><i /><i /><i /><small>Illustrative map preview</small></div><div className="state-card"><span className="illustrative">Selected state · illustrative</span><h3>West Bengal</h3><div><span>Pending cases</span><strong>18.2 lakh</strong></div><div><span>Active courts</span><strong>320</strong></div><Link href="/whats-mocked">Explore court data →</Link></div></div></div></section>
  <section className="roles wrap" id="roles"><div className="center-heading"><p className="kicker">One system, multiple journeys</p><h2>Built around the people who carry a case forward.</h2></div><div className="role-grid">{roles.map(([role, text], index) => <Link href={`/roles/${role.toLowerCase().replaceAll(" / ", "-").replaceAll(" ", "-")}`} className="role-tile" key={role}><span className={index < 2 ? "demo-pill" : "prototype-pill"}>{index < 2 ? "Demo" : "Prototype"}</span><h3>{role}</h3><p>{text}</p><span className="arrow">Explore →</span></Link>)}</div></section>
  <section className="how-it-works"><div className="wrap"><div className="center-heading"><p className="kicker">How Nyaya works</p><h2>A clearer way to stay informed.</h2></div><div className="how-grid"><div><span>01</span><h3>Find your case</h3><p>Search using available case information.</p><Link href="#track">Search →</Link></div><div><span>02</span><h3>Follow your case</h3><p>Keep relevant cases together in one place.</p><Link href="/login">Create account →</Link></div><div><span>03</span><h3>Stay informed</h3><p>Receive meaningful updates when something changes.</p><Link href="/roles/litigant">See dashboard →</Link></div></div></div></section>
  <section className="final-cta"><div className="wrap"><p className="kicker">Start here</p><h2>Your court journey,<br /><em>easier to follow.</em></h2><p>Start by finding a case or exploring available services.</p><div><Link className="brass-cta" href="#track">⌕ Find a case</Link><Link className="outline-cta" href="#services">Explore services <span>→</span></Link></div></div></section>
</main><Footer /></>; }
