import Link from "next/link";
import CaseLookup from "@/components/CaseLookup";
import PortalUnifier from "@/components/PortalUnifier";
import { Disclaimer, Footer, Header } from "@/components/SiteChrome";
import SystemFlow from "@/components/SystemFlow";
import RoleExperience from "@/components/RoleExperience";
import IndiaCourtMap from "@/components/IndiaCourtMap";
import FindCaseMenu from "@/components/FindCaseMenu";
import { createPageMetadata } from "@/lib/seo";

export const metadata = createPageMetadata("Unified Digital Court Services", "Explore a clearer prototype for finding cases, following hearings, viewing court documents, and understanding India’s digital court journey.", "/");

const unifiedCaseHref = "/cases/NYA-WB-DEMO-04821";
const actions = [["⌕", "Find a case", "Search the bundled synthetic court records.", "/find-case"], ["+", "File a fresh case", "Explore the local, designed-only filing journey.", "/file-a-case"], ["◴", "Today in court", "View demo cause lists and upcoming hearings.", "/today"], ["⌁", "Understand", "Learn how courts, stages and procedures work.", "/nyaya-guide"]];
export default function Home() { return <><Disclaimer /><Header /><main>
  <section className="journey-hero" id="track"><div className="wrap hero-layout"><div className="hero-copy"><p className="kicker">Information about a case</p><h1 className="service-hero-title"><span>E-Court Services</span><em>Unified Interface for Citizens, Advocates, Court Staff</em></h1><p className="lede">Find case information, understand court updates, and see what happens next — without a login or a fragmented search.</p><CaseLookup /><div className="workspace-entry"><span>I work in the justice system</span><Link href="/login">Access My Workspace <b>→</b></Link></div></div><div className="hero-unifier"><span className="visual-caption">A case journey, made clearer</span><PortalUnifier /></div></div></section>
  <FindCaseMenu />
  <section className="actions wrap" id="services"><div className="center-heading"><p className="kicker">Start with your need</p><h2>What do you need to do today?</h2><p>You shouldn&apos;t need to know which system to visit.</p></div><div className="action-grid action-grid-four">{actions.map(([icon, title, text, href]) => <Link className="action-card" href={href} key={title}><span className="action-icon">{icon}</span><h3>{title}</h3><p>{text}</p><span className="arrow">→</span></Link>)}</div></section>
  <section className="unification"><div className="wrap unify-layout"><div><p className="kicker">Why Nyaya exists</p><h2>The justice system is connected.<br /><em>The digital experience shouldn&apos;t feel disconnected.</em></h2><p>Nyaya is a conceptual experience layer designed around people, cases and workflows. It does not replace or control court systems.</p><p className="unify-note">One identity. One case timeline. A simpler way to stay informed.</p></div><div className="conceptual-network"><span>Case status</span><span>Cause lists</span><span>Documents</span><span>Orders</span><div><b>NYAYA</b><small>Unified case</small></div><span>Filing</span><span>Hearings</span><span>Notifications</span><span>Action items</span></div></div></section>
  <section className="case-journey wrap"><div className="center-heading"><p className="kicker">Your case, explained like a journey</p><h2>A case is more than a status.<br />It&apos;s a journey.</h2></div><article className="journey-card"><div className="journey-card-head"><span className="case-id">NYA-WB-DEMO-04821</span><span className="demo-pill">synthetic demo</span><h3>Sharma v. State of West Bengal</h3></div><div className="journey-steps journey-steps-extended"><span className="complete">Filed</span><span className="complete">Under scrutiny</span><span className="complete">Registered</span><span className="complete">Hearing</span><span>Evidence</span><span>Arguments</span><span>Judgment</span><span>Appeal</span></div><div className="journey-explainer"><div><span className="illustrative">Current stage</span><h3>Hearing scheduled</h3><p>Your next hearing is scheduled for 26 August 2026.</p></div><div><span className="illustrative">What may happen next?</span><p>The court may hear submissions, record evidence, or issue further directions. This cautious explanation is illustrative.</p></div><Link className="outline-cta" href={unifiedCaseHref}>Open unified case <span>→</span></Link></div></article></section>
  <SystemFlow />
  <RoleExperience />
  <section className="court-data" id="court-data"><div className="wrap"><IndiaCourtMap /><Link className="court-data-link" href="/courts">Explore court data →</Link></div></section>
  <section className="how-it-works"><div className="wrap"><div className="how-heading"><div><p className="kicker">How Nyaya works</p><h2>A clearer way to stay informed.</h2></div><p>Start with the case. Nyaya keeps its important updates, documents and next steps in one calm workspace.</p></div><div className="how-grid"><article><div className="how-step"><span>01</span><i>⌕</i></div><h3>Find your case</h3><p>Search by a synthetic case ID, party or advocate to open one shared record.</p><Link href="/find-case">Search a case <b>→</b></Link></article><article><div className="how-step"><span>02</span><i>◌</i></div><h3>Follow the journey</h3><p>See hearings, filings, documents and attention items in their procedural context.</p><Link href="/login">Open My Nyaya <b>→</b></Link></article><article><div className="how-step"><span>03</span><i>↗</i></div><h3>Act with clarity</h3><p>Review what changed, what is next, and where a human review may be needed.</p><Link href={unifiedCaseHref}>View the demo case <b>→</b></Link></article></div><p className="how-disclosure">Built for a synthetic prototype journey. Nyaya does not connect to live court systems.</p></div></section>
</main><Footer /></>; }
