"use client";
import { useState } from "react";
import indiaMap from "@svg-maps/india";
import { demoCourtData } from "@/data/demo-court-data";

export default function IndiaCourtMap() {
  const [selected, setSelected] = useState("Delhi"); const current = demoCourtData.find((item) => item.state === selected)!;
  return <section className="dashboard-map" aria-labelledby="court-data-dashboard"><div className="map-heading"><div><p className="kicker">Court data</p><h2 id="court-data-dashboard">Explore a state preview.</h2></div><span className="illustrative">All values illustrative · local only</span></div><div className="map-dashboard-grid"><div className="india-selector"><svg className="india-map-svg" viewBox={indiaMap.viewBox} role="img" aria-label="Interactive vector map of India with state boundaries"><title>India state map</title>{indiaMap.locations.map((location: { id: string; name: string; path: string }) => { const available = demoCourtData.some((item) => item.state === location.name); const active = selected === location.name; return <path key={location.id} d={location.path} className={`map-region${available ? " available" : ""}${active ? " active" : ""}`} onClick={() => available && setSelected(location.name)} onKeyDown={(event) => { if (available && (event.key === "Enter" || event.key === " ")) setSelected(location.name); }} role={available ? "button" : undefined} tabIndex={available ? 0 : -1} aria-label={available ? `Select ${location.name}` : `${location.name}: no preview data`} />; })}</svg><p>Select a highlighted state to update the local preview. Map geometry is a local vector asset; it is not an official boundary representation.</p></div><div className="state-preview"><span className="illustrative">Selected state · {current.note}</span><h3>{current.state}</h3><div><span>Pending cases</span><strong>{current.pending}</strong></div><div><span>Active courts</span><strong>{current.courts}</strong></div><div><span>Average case age</span><strong>{current.averageAge}</strong></div><div className="mini-trend"><span>Illustrative activity</span><svg viewBox="0 0 190 50" aria-hidden="true"><path d={current.trend === "up" ? "M3 39 C32 35 49 42 77 25 S132 27 187 10" : "M3 12 C34 15 53 7 78 24 S132 30 187 40"} /></svg></div></div></div><div className="map-state-list" aria-label="Choose a state">{demoCourtData.map((item) => <button className={item.state === selected ? "selected" : ""} onClick={() => setSelected(item.state)} key={item.state}>{item.state}<span>{item.code}</span></button>)}</div><p className="map-attribution">India vector map geometry: <a href="https://github.com/VictorCazanave/svg-maps" target="_blank" rel="noreferrer">svg-maps</a> (CC BY 4.0). Data shown is Nyaya&apos;s local synthetic demo data.</p></section>;
}
