"use client";
import Link from "next/link";
import { useState } from "react";
import { Disclaimer, Footer, Header } from "@/components/SiteChrome";
import { setMockRole } from "@/data/mock-session";
import { roleConfig, roleHome, type Role } from "@/data/roles";

const roles: Array<[Role, string, boolean]> = [["citizen", "Track a case, understand updates, and follow next steps.", false], ["advocate", "Manage matters, hearings, deadlines, and case documents.", true], ["judge", "View docket and readiness context. Decisions remain human.", true], ["registry", "Work with filing intake, scrutiny, and registration queues.", true], ["stenographer", "Review assigned proceedings and synthetic draft workflows.", true], ["police", "View authorised case-linkage and document-status workflows.", true]];
export default function Signup() { const [role, setRole] = useState<Role | null>(null); const [review, setReview] = useState(false); const [open, setOpen] = useState(false); const institutional = role ? roles.find(([name]) => name === role)?.[2] === true : false; function selectRole(name: Role, requiresReview: boolean) { setRole(name); setMockRole(name); setReview(false); setOpen(requiresReview); } return <><Disclaimer /><Header /><main className="wrap auth-page"><p className="kicker">Role onboarding · mock only</p><h1>Set up your Nyaya profile.</h1><p className="auth-intro">Choose how you would primarily use Nyaya. This does not create an account, submit information, or grant real access.</p><section className="role-select full-role-grid" aria-label="Choose a mock role">{roles.map(([name, description, requiresReview]) => <button type="button" onClick={() => selectRole(name, requiresReview)} className={role === name ? "selected" : ""} key={name}><span>{requiresReview ? "Authorised role" : "Public role"}</span><b>{roleConfig[name].label}</b><small>{description}</small></button>)}</section>{role && !institutional && <section className="signup-selected"><b>{roleConfig[role].label} selected</b><p>Start with a public, case-focused experience using synthetic prototype data.</p><Link className="login" href={roleHome(role)}>Continue to mock workspace →</Link></section>}{open && role && <div className="signup-modal-backdrop" role="presentation"><section className="signup-modal" aria-modal="true" aria-labelledby="role-review-title" role="dialog"><button className="modal-close" aria-label="Close" onClick={() => setOpen(false)}>×</button><span className="illustrative">Selected mock profile</span><h2 id="role-review-title">{roleConfig[role].label}</h2><p>Institutional and professional roles require verified organisational access in a real product. This demo does not ask for, accept, or process certificates, identity numbers, or uploads.</p><div className="compliance-placeholder"><b>Compliance review — simulated</b><span>Professional credential / organisation authorisation</span><span>Role assignment / access approval</span><span>Human review before access</span></div><label className="review-check"><input type="checkbox" checked={review} onChange={(event) => setReview(event.target.checked)} /> I understand this is a simulated authorisation flow with no real verification.</label><Link className={review ? "login" : "login disabled-link"} href={review ? roleHome(role) : "#"} aria-disabled={!review}>Continue to mock workspace →</Link></section></div>}<p className="auth-switch">Already exploring? <Link href="/login">Open a demo session →</Link></p></main><Footer /></>; }
